resolver: lts-6.0
packages:
- 'gonimo-back'
- 'servant-purescript'
- 'servant-subscriber'
- 'purescript-bridge'
- 'servant-purescript/examples/central-counter'
extra-deps:
  - aeson-0.11.2.0
  - freer-0.2.2.6
  - purescript-bridge-0.6.0.0
flags: {}
